### ISSUE TITLE
throwing an error after test.finish() node exists, rather than registering a failure

### ISSUE THREAD

**Issue by dominictarr** [bentomas/node-async-testing#1]
if an error is thrown after test.finish() is called node exits. 
this is a confusing error at best.

```
  exports['test error'] = function (test){
      test.finish();
     throw new Error('test should error');
  }

  if (module == require.main) {
    require('async_testing').run(__filename, process.ARGV);
  }
```

**Comment by bentomas** [comment]
When you are calling `test.finish` you are saying that the test is done.  There is no way to know that the error is with that test because node-async-testing has already wrapped the test up and began the process of starting the next test.  I think the error comes from the fact that it has finished the test and queued the next test but the next test hasn't actually started (it will after the `nextTick`).  I would love some suggestions on how to make this better at handling these sort of errors.  But I can't really second guess the `test.finish()` call, I have to trust that the test is truly finished, otherwise what's the point?

One thing I can do is actually make `test.finish()` itself throw, so the rest of the function isn't run, but I don't know what sort of affect that will have an a lot of changes I'm going to push in the next couple days to add better support for teardown functions.  I'll have to check it out. 

In the meantime, you can write all your `test.finish()` calls like this:

```
return test.finish();
```

To make sure that no more code in the function is run.  However, neither of those solve the asynchronous case:

```
function(test) {
  setTimeout(function() {
    test.finish();
  }, 500);
  setTimeout(function() {
    throw new Error();
  }, 1000);
}
```

But I think this is going to be the case in any asynchronous testing library.  If it isn't, I'd love to see how someone solved it!  

In fact, I've decided that I've been trying to be way to clever about errors anyway.  In the next version of node-async-testing, an error will stop the running of a suite completely.  It will try to guess which test caused the error (but would be wrong in the previous examples), and then exit that suite.  This makes a lot of things a lot easier to do.  The thinking being that an _error_ is a show stopper anyway.

But once again, any ideas on how to address these problems differently would be welcome!

Sorry, I can't provide a better solution.

**Comment by dominictarr** [comment]
hey

I've been thinking about this all afternoon now, and I have a few ideas:
1. process.on('uncaughtException',...) is unfortunately catch-all, there is no way to cordon off part of the program like you could in a synchronous enviroment by wrapping a block of code in try/catch, and having every error below that point in the stack get caught.
   
     I've been considering some way to get multiple process objects, including invoking http://github.com/ry/node/blob/master/src/node.js with another a different process object. this idea has potential, it's crazy and thats why i like it, potentially, it would mean you can have another event loop, and so errors thrown in callbacks could get caught by process.on('uncaughtException',...) on a different process object. 
   
     however, I don't know whats happening with error which originate inside the C parts of node, so they might still get through.
2. the simple way of providing another process object is just to spawn a child node process and running a test in that. this adds the complication of inter process communication, but should be rock solid. there would be no way for the test subject to monkeypatch the main process or break anything. this seems like a heavy weight solution, but with multi-core and a managed process pool it might be fast anyway.
   
     I am actually working on this problem already, although I was intending on running each test suite in a separate process rather than each _test_. I've just started, using http://github.com/substack/dnode for the IPC.
3. don't do anything clever, but make a better error message. if an error is thrown or an assertion is made after test.finish() is called then consider that a error in the test's logic - i.e. not an error in the test subject, but an error in the test. I think this should say, still callback to onSuiteDone but give a report that says the test was invalid due to a assertion/error after test.finished()

idea 3 seems the most realistic, right now, 

anyway, I'm very interested in where you a looking to take this project and would like to help. 
apart from this i'd like to add support for things like giving each test a set time to run in, and being able to treat the test not finishing as some sort of regular error. 

I'd also like to write some tight tests for async_testing, as i belive a testing framework should be well tested!

what features are planning on adding, i'd like to keep my efforts in line with your plans, also!

cheers. Dominic

**Comment by bentomas** [comment]
Yeah, I like 3 the best.

I'd rather not monkey around with Node internals, so until [1] is added to core, that seems like a lot of work.  

I think [2](a process per test) is overkill.  Though, I supposed without some testing to see how that affects things, I don't have much to back that up with.  I wonder how many child processes Node can open at once. I'm think the limit there would be the Node thread pool size.

However, it was actually on my todo list for next weekend to make it so each suite is launched as a child process so they can all run at once.  This would make things a lot faster.  It would need to be optional (in case different suites are accessing a common database or something), but would be very slick.  The web runner already runs each suite in a child process (though still only 1 suite at a time), so it is doable.  However, it depends on node-webworker, which is a dependency I'd like to remove.  There doesn't really need to be all that much 2 way communication between the runner and the child process, so I think it could be done simpler than the node-webworker.  DNode looks very interesting as well.  Do you think it is a big deal to have a dependency for that sort of thing?  If not then my webworker implementation already works, but needs to be moved into the console runner.

Any help in getting that to work would be awesome.  

As far as number 3, I would have thought that it would have just assumed the error was in the _next_ test, since the other test already finished.  I think 2 things need to be changed:
1.  test.finish() should throw a particular kind of error that we catch (kind of like the way assertions work), so that no more code in functions is ran.
2. make it so we do something particular in the uncaughtException handler if it gets an error but there are no tests listed as running.  Maybe we should just blame it on all the tests that have already finish, since we have no real clue which one it was that caused it.  I just pushed the change to the way error handling is done that I mentioned before, so I don't know if this will address the problem.

My immediate plans are to work on finishing proper setup/teardown support.  Right now if a test fails then teardown (via the `wrap` function) will never run, which sort of defeats the purpose of having a function that is run after _every_ test.  I just pushed a working implementation that fixes this but am working on some documentation.  (and am updating all the documentation in general).

All the suites in the test directory are all there for explicitly testing async_testing but also have the added benefit of being examples.  I've added a few for the setup/teardown/control flow code I just wrote that I think are pretty exhaustive.  Once again, if you see some areas where it could use better testing, I'd love that.

**Comment by bentomas** [comment]
I started work on running suites in a child process last night.  It is going well.

I've been thinking more about your suggestion "to treat the test not finishing as some sort of regular error."  That sounds really cool and tried to make it work, but I'm not sure it is possible.  The only way to know if a test never finished is when the process is exiting (otherwise we have to assume it is still doing something), which we know from the process' exit event.   At that point we can't treat it like a normal test result because this will potentially cause more tests to be run or more suites, but "The main event loop will no longer be run after the 'exit' callback finishes, so timers may not be scheduled." So we can't actually run more code.  If you can think of a way of knowing if a test hasn't finished besides the process' exit event let me know.

**Comment by bentomas** [comment]
I added a todo list of all the things I am thinking about doing or want to do: http://github.com/bentomas/node-async-testing/blob/master/todo.txt

**Comment by bentomas** [comment]
Also, I committed the support for running suites in parallel that we talked about!  Let me know if it causes any problems.

You have to trigger it on the command line:   

```
node test/test-* -P
```

To run both the suites and the tests in parallel:

```
node test/test-* -P -p
```

Also, right now the child process can be told what tests it is supposed to run, so it isn't a stretch to think about running each test in its own child process.  Maybe down the line we can look into that!

**Comment by dominictarr** [comment]
hey, just getting well into this today.

started working on your args thing at the top of the todo list to warm up,
but I want to have real tests for async_testing before I actually change something because I dont want to break stuff.

I wouldn't consider the tests in ./test to be propper tests, because they print out the error report, but with messages that say what the test should be, so you still have to go through and read each one to make sure it's right... which is manual testing. what i'm working on right now is a way to run those tests, and then check that they have the right output, so that if everything is working right there is a green light...

and also to test other essential things about the interface, such as that onSuiteDone is always called... 

I've got this afternoon's work at http://github.com/dominictarr/meta-test, this is still VERY hacky. and needs to be tidied, but, it does run some simple async_testing tests and checks there results. depends on DNode,

which is a fairly heavy dependency, but my design philosophy is to get behaving right, asap, and then tidy up, and trim it down - improving performance, but without changing the interface.

**Comment by bentomas** [comment]
I'll look into this meta-test more tonight, but wanted to warn you that I worked on the args stuff this evening and got it mostly taken care of.   I'll try and get it pushed soon.

I'm excited about this idea of testing async_testing itself better.  It is definitely a manual process right now.

**Comment by dominictarr** [comment]
no problem, I think I was getting too clever with the args thing anyway...
and meta-testing is the big fish...

**Comment by bentomas** [comment]
Let me see if I am understanding meta-test right, It runs the code in a child process (using dnode) and then makes assertions about what gets written to stdout?  

I'm hesitant to go that route for 2 reasons
1. I'm not sure it will properly test all the nuances of what is going on.  We need to make sure that certain things happen in a specific order. Like, after this test finishes in this way, this particular callback is fired. And just looking at the output isn't necessarily going to be able to catch that all that.  Though, I suppose if you write enough tests, your output should get the different scenarios.  I'm just worried about making some assumptions about the actual timing of things that just looking at the static output won't catch.
2.  It makes it hard to test new functionality or change the output because you have to maintain by hand the strings you want it to write to stdout.  Or can I just copy and paste my output into a file and it compares them?

What I did for the tests in test/flow/\* was actually create all the tests programmatically. I specified all the different scenarios I wanted and then it ran through them.  Unfortunately right now, the only way to double check the order is to look at a large console.log() dump which shows when each test ran what, by hand.  I think it would be cool to write code where you can define what you want your tests to look like, and then it would create the tests, run `runSuite()` itself and verify the callbacks as they happen and the test flow as it happens. That's a lot of work though.

I don't mean to discourage you about meta-test at all, I'm just saying that it is a hard problem and I am still undecided about how exhaustive its testing will be.

 I'm excited to see where you take it.

**Comment by dominictarr** [comment]
hey, sorry i didn't mean to say that i was checking the stdio...

i'm checking the callbacks. see the commit i just made. 

getting a little tidier now. I have tests for the correct output/behaviour for onSuiteDone and onPrematureExit for a new simple passing,failing and erroring tests. 

although, I'm afraid it's only compatible with async_testing 0.3.2, it's just that that is the interface i'm familiar with and I wanted to get a foot hold asap.

**Comment by dominictarr** [comment]
oops, accidentially clicked comment and close...

**Comment by bentomas** [comment]
Oh! I see how it works now!  AND IT'S TOTALLY AWESOME.

I understand it only being compatible with version 0.3.2, I've been on a bit of a tear lately adding features (though, things should be settling down now, got all the major things on my todo list done!).

I'm going to be busy this week working on a deadline, so I'm not going to be able to spend as much time working on node-async-testing as I have this last month. But I'm very excited about this, and can't wait to use it more!

**Comment by bentomas** [comment]
So, I've been thinking about this some more.  Here are the two things that I would want from this kind of testing:
1.  To verify that the methods finish the way we expect them to.  Test X passes or fails and if it fails, it fails in Y way.
2.  To make sure that the methods for the tests (like setup and teardown) are executed in the order we expect them to be.

Currently meta-test is great at the first one.  My other thought is that testing your test library should be as simple as possible.  The more code it does the more chance there is for there to be a bug in the testing-testing code. Currently meta-test uses node-async-testing to test node-async-testing, which seems to be potentially problematic.  Plus it depends on Dnode for communication.  Another spot for things to go wrong.

The tests for node itself don't use a testing framework, it is just comprised of a bunch of scripts that make assertions, so when there is an assertion failure the thrown error is just printed.  Very simple.  I think we should be doing something similar, just making assertions about what we expect a test to do.

Also, it would be cool to put the expected results of a suite in a file (like test-suite.json) so that way it is easy to look at a suite and what you expect it to do, and you don't have to go in and edit code.

I threw together a few of these ideas into a simple script (it uses the new async_testing.runFile method for running suites in a child process): http://gist.github.com/657424 To run it you just type:  

```
node verify.js test-suite.js
```

I also included in a gist example results file for the suite. 

Let me know what you think!

**Comment by dominictarr** [comment]
I think your definitely on to something here,

I'd been so obsessed with big clever ideas about testing that i neglected the simplest possible way to make a test. just running a script which errors or not may not give the best reporting, but it's better than nothing.

A simple script which errors or doesn't is a completely valid test. If it is completely simple. if it is not sufficient simple there is the danger that the test itself has errors. 

that would produce a false negative.

A test should be simple enough so that a programmer who knows the language could just read through it an see that nothing overly complex is happening (except from inside the test subject), this way false negatives can be reasonably eliminated.

If there is something complex inside the test, then that thing needs to be well tested so that you can get examples of it's use and be confidant about it's behavior by running the tests.

Although meta-test is complex and has complex dependencies, meta-test and all it's dependencies have tests. 

And meta test has a very simple interface, which is nearly the same as async_testing so the test itself is completely simple.

It's basicially just runs the test, callsback the result, and then checks that the result matches a hard coded example.

I'm all for simple script-test but only if it is truly simple, it it has tests for it's complex parts.

looking at your gist I cant quite immediately see what it does, no actually, verify.js looks quite good.. it's still a little more complex than simple, but it's not yet complicated. 

however I can't find any example .json files for your tests... so i can't run it yet. also, you will run into complications with the tests being too tight.

for example, when you assert.equal the test stdout with the expected test stdout (copied and pasted from a known-valid run), and then edit the code, the line/column numbers in the stack trace of the error messages will change, but still be correct. maybe test that the error message occurs in the stdout more than that is probably overkill for a unit test.

I think verify.js is complex enough that it needs it's own test. had I written verify.js i would have begun by writing a test for it...

have you seen this article: http://www.objectmentor.com/resources/articles/xpepisode.htm ?

**Comment by bentomas** [comment]
I'm perfectly happy with using Meta-test!  It is working already and works great!

I think both approaches are actually pretty similar. For verify.js I just used node-async-testing's `runFile()` method to actually run each test in a child process (as opposed to another library like Dnode).   I can't decide if that is an advantage or disadvantage.  My gut says it is an advantage.  (since we'd be testing that too, but I realize the dangers of trying to test too much at once).

The stdout comparison was for addressing my second desire from a "meta" testing library which is to be able to make sure multi-function tests are called with their functions in the right order and at the right times (e.g. setup/teardown).  It was not for comparing test output from the console runner.  In a suite I'm testing, I could say (and I did this in flow-raw.js of the gist) `console.log()` something in each test function, and then I could assert that what was outputted, was done so in the right order. The thought being that you DON'T copy and paste the output, but actually write up the order you expect the tests to run yourself and then verify that it works that way.

So if a test has three functions (A, B, and C) then I could say that in serial mode those three functions should happen right in a row, but in parallel (and assuming some of them are async) (A) will happen and then other tests functions, and then (B), and so on.  

Basically, I want fine grained control over making sure that the flow of node-async-testing is what it is supposed to be.  Right now it is a very painful, manual process of making toggling whether certain tests async or not and then manually looking at the STDOUT setup I describe above.

[I just realized that if you had tried to run `verify.js` yourself it wouldn't have worked (I had to patch the `runFile` function for <stdout> stuff).  Sorry!]

Do you have any ideas on how to handle that sort of testing in meta-test?

Also, I think having the expected results in a file is really useful.  An example file is in the gist here: https://gist.github.com/657424#file_flow_raw.json  Right now that file is just saying what it expects when running the tests in seria. If the result for a test is marked as `false` then you are saying it doesn't fail, and if it is anything 'truethy' it should fail.  If the expected result is a string it is the error message of the failure. 

Tests can behave differently depending on whether or not they are run in parallel, so being able to make assertions depending on the situation seems important.

So, I guess those are my three feature requests for meta-test:

1) Be able to make assertions about suite/test flow (setup/teardown/suiteSetup/suiteTeardown).
2) Store the expected output for a suite in a file next to the suite (for easy comparison/editing)
3) Be able to make different assertions depending on whether or not the tests are being run in parallel or not.

Either way, as we move forward with better/more/actual automated testing for node-async-testing I think we should probably separate example suites from actual node-async-testing suites.  So maybe add an `examples` folder.  The thought being that actual tests need to be pretty exhaustive and won't necessarily be all that easy for newcomers, but we still need a resource like that for newbies.

Sorry to be difficult! Thanks for working through this with me.

What do you think?

(I haven't read that article yet, it looks pretty long!  I've added it to my list of articles to read on my Desktop and will get to it once things die down at work a little! Thanks!)

**Comment by dominictarr** [comment]
ah, okay, now i see what you where doing with flow-raw... using stdout to record a function seems fragile, since using console.log to debug something might break the test, although it might still actually work right. it is nice in that it's a very light weight way to the sequence out. 

another way of looking at this is mocking the tests and checking that the test framework responds correctly. you know what i mean? http://en.wikipedia.org/wiki/Mock_object, the problem of making tests about call order is something you'd want to test in many async projects. 

i'm gonna have to think about this a little more... but i think using callbacks would be a more general solution than stdout.

ditto on the test/example folder although I like to use a test/.examples to keep all the resources needed for the test. 

which reminds me, sometimes you need things like external resources for a test (maybe a database or something), and the test will fail if it's not there, but it's not the same as the test subject having an error because it's a dependency of the test. it's a seperate case: the test can't be run properly because of a missing dependency...

i think there needs to be a way to handle this... say something like:

```
test.prereq.ok(checkDatabaseIsUp(),"need test database "testme" on localhost:5432") 
```

or maybe allow assertions in the setup method...

which fails the test with a 4th status, "invalid" or something...we would use this to check that the .example files are actually there... or to check that helper methods for the test actually work.

this afternoon i'm gonna do a bit more thinking about this test mocking business, and port meta-test to async_testing 0.4.x

i'd fully recommend reading that article. it's gold.

cheers

**Comment by bentomas** [comment]
Sorry I have been MIA, mom's visiting and work has been busy.  Hopefully things will calm down soon.
